// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/hello.proto

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	api/hello.proto

It has these top-level messages:
	GreetingRequest
	GreetingResponse
*/
package hello

import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GreetingRequest) Validate() error {
	if this.Name == "" {
		return go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must not be an empty string`, this.Name))
	}
	return nil
}
func (this *GreetingResponse) Validate() error {
	if this.Message == "" {
		return go_proto_validators.FieldError("Message", fmt.Errorf(`value '%v' must not be an empty string`, this.Message))
	}
	return nil
}
